# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firebaseTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebaseTest
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestoreSwift'

  # Pods for sidemenu
    pod 'SideMenu'

  # Pods for google sign in
    pod 'GoogleSignIn'

end
